title: What's That Function?
description: Quick and simple coding tutorial videos
show_downloads: false
collections:
  functions:
    output: true
    sort_by: fn
    permalink: /:path

url: https://whats-that-function.com

backgroundcolor: "#75d7ce"
headingcolor: "#ff3900"
fncolor: "#f3ff55"

google_analytics:
