title: What's that function
description: Quick and simple coding tutorial videos
show_downloads: false
collections:
  functions:
    output: true
    sort_by: fn
    permalink: /:path

domain: https://whats-that-function.com

google_analytics:
