title: What's That Function?

description: Quick and simple coding tutorial videos

logo: /assets/logo.png
url: https://whats-that-function.com

# google_site_verification:
#   google:

backgroundcolor: "#75d7ce"
headingcolor: "#ff3900"
fncolor: "#f3ff55"

collections:
  functions:
    output: true
    sort_by: fn
    permalink: /:path
